### PR TITLE
fixed bug where child processes would also get registered with consul

### PR DESCRIPTION
**Pull request by aaivazis**
@janjaapbos can you verify that this prevents the sub-process from being registered with consul?

### CODE REVIEW

**Comment by janjaapbos** [comment]
No it still has two instances per service registered.

**Comment by aaivazis** [comment]
damn, alright i'll try to figure this out when i get back from lunch

**Comment by janjaapbos** [comment]
So actually this does appear to solve the problem that requests are routed to the wrong service model. Still having instances of the model registered though, and also mutations are done twice.

**Comment by aaivazis** [comment]
I just tested this locally and confirmed that only a single instance of any given service is registered when it runs

**Comment by janjaapbos** [comment]
I see where my issue comes from, when I start the service with the --debug flag I have two instances running of the same. At the prompt it is notified as a restart, but apparently the original consul registration is not closed.

/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.0.12-py3.4-linux-x86_64.egg/sqlalchemy/ext/declarative/api.py:173: SAWarning: Unmanaged access of declarative attribute __tablename__ from non-mapped class BaseModel
  (desc.fget.__name__, cls.__name__))
 * Running on http://0.0.0.0:8001/ (Press CTRL+C to quit)
 * Restarting with stat
/usr/local/lib/python3.4/dist-packages/SQLAlchemy-1.0.12-py3.4-linux-x86_64.egg/sqlalchemy/ext/declarative/api.py:173: SAWarning: Unmanaged access of declarative attribute __tablename__ from non-mapped class BaseModel
  (desc.fget.__name__, cls.__name__))
 * Debugger is active!
 * Debugger pin code: 148-648-910
  

Without the --debug flag it works correctly, only a single instance is registered.

**Comment by janjaapbos** [comment]
Removing the --debug flag also solves the double mutations.

**Comment by aaivazis** [comment]
Ha! That explains why I wasn't seeing it. Let's remove that flag as part of this pr since its part of the fix. I'm on my phone atm - mind doing that?

**Comment by janjaapbos** [comment]
That would be the easy way. ;-)

I would like to be able to use the debug mode. I think it is due to the code reloader. See: http://stackoverflow.com/questions/31264826/start-a-flask-application-in-separate-thread

So we can use that option: app.use_reloader=False
I just checked that this solves the issue while still running with debug mode.

Or perhaps some global variable can be set that is not reinitialised with the code reload, and check that variable for an active consul session before starting it.

**Comment by janjaapbos** [comment]
I have created a PR with the fix.

**Comment by aaivazis** [comment]
Looks good to me - I went ahead and made some changes to the way we handle the sub-process but the outcome should be the same. Please verify this in case I messed something up

**Comment by aaivazis** [comment]
Great find btw, that would have taken me *a lot* of digging to find the culprit

**Comment by janjaapbos** [comment]
Yes, this works fine for me!

2016-03-12 19:25 GMT+01:00 Alec Aivazis <notifications@github.com>:

**Pull request merged**
